{"name": "Тест авторизации несуществующего пользователя", "status": "passed", "description": "Проверка, что авторизация под несуществующим пользователем вызывает ошибку 404", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "body", "value": "{'login': 'nonexistent_user_login', 'password': 'nonexistent_user_password'}"}], "start": 1726528252372, "stop": 1726528252502}], "start": 1726528252372, "stop": 1726528252502, "uuid": "87d5ec95-52f4-4350-9668-c0f6ea531444", "historyId": "f5eb39f284df88e437a34e9526e32e76", "testCaseId": "f5eb39f284df88e437a34e9526e32e76", "fullName": "tests.test_login_courier.TestAuthorizationEndpoint#test_login_with_nonexistent_user", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestAuthorizationEndpoint"}, {"name": "host", "value": "NB-MP2CT5HP"}, {"name": "thread", "value": "73104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}